{% set name = 'pyfftw' %}
{% set version = '0.9.2' %}
{% set number = '2' %}

about:
    home: http://hgomersall.github.com/pyFFTW
    license: BSD
    summary: |
        A pythonic wrapper around FFTW, the FFT library, presenting a unified
        interface for all the supported transforms

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - fftw
    - cython
    - pkg-config [osx]
    - setuptools
    - numpy
    - python x.x
    run:
    - cython
    - fftw
    - numpy
    - python x.x

source:
    fn: pyFFTW-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-{{ version }}.tar.gz

test:
    imports:
    - pyfftw
