{% set name = 'nictools' %}
{% set version = '1.1.3' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    summary: |
        Python tools for NICMOS data

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - numpy
    - scipy
    - stsci.distutils
    - stsci.tools
    - setuptools
    - python x.x
    run:
    - astropy >=1.1
    - numpy
    - scipy
    - stsci.tools
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - nictools
