{% set name = 'stsci.skypac' %}
{% set version = '0.9.5' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: stsci.skypac

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - stsci.distutils
    - stsci.imagestats
    - stsci.sphere
    - stsci.tools
    - stwcs
    - setuptools
    - numpy
    - python x.x
    run:
    - astropy >=1.1
    - stsci.imagestats
    - stsci.sphere
    - stsci.tools
    - stwcs
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.skypac
