{% set name = 'fftw' %}
{% set version = '3.3.4' %}
{% set number = '0' %}

about:
    home: http://www.fftw.org
    license: GPL
    summary: |
        A fast, free C FFT library; includes real-complex, multidimensional, and parallel transforms

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - pkgconfig
    run:
    - pkgconfig

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: http://www.fftw.org/{{ name }}-{{ version }}.tar.gz
