{% set name = 'qtpy' %}
{% set version = '1.1.1' %}
{% set number = '2' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/{{ name }}/QtPy-{{ version }}.tar.gz
  md5: 181a1cc9c010e0c1f4daa3f0f69e3782

build:
  number: {{ number }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pyqt
  imports:
    - qtpy

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  summary: A uniform layer to support PyQt5, PyQt4 and PySide with a single codebase

