{% set name = 'pydrizzle' %}
{% set version = '6.4.4' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Geometrically correct and combine images using Drizzle

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - setuptools
    - stsci.distutils
    - stsci.tools
    - numpy
    - python x.x
    run:
    - astropy >=1.1
    - stsci.tools
    - wxpython [py27]
    - numpy
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - pydrizzle
