{% set name = 'gwcs' %}
{% set version = '0.7' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Generalized World Coordinate System

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - asdf
    - astropy >=1.1
    - setuptools
    - numpy
    - python x.x
    run:
    - asdf
    - astropy >=1.1
    - numpy
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - gwcs
