{% set name = 'pyqtgraph' %}
{% set version = '0.10.0' %}
{% set tag = name + '-' + version %}
{% set number = '0' %}

about:
     home: http://www.pyqtgraph.org/
     license: MIT
     summary: |
         A pure-Python graphics library for PyQt/PySide

build:
     number: {{ number }}

package:
     name: {{ name }}
     version: {{ version }}

requirements:
     build:
     - setuptools
     - numpy
     - python x.x
     run:
     - pyqt
     - pyopengl
     - numpy
     - python x.x

source:
     git_tag: {{ tag }}
     git_url: https://github.com/pyqtgraph/{{ name }}.git

test:
   imports:
     - pyqtgraph
