{% set name = 'glue-vispy-viewers' %}
{% set version = "0.7.2" %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/{{ name }}-{{ version }}.tar.gz
  md5: 58cd60967ed1b80b965b0627b2d3bd77

build:
  number: {{ number }}
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyopengl
    - glue-core >=0.10

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=0.10
    - matplotlib
    - qtpy
    - pyqt

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue
