{% set name = 'fitsblender' %}
{% set version = '0.3.1' %}
{% set number = '0' %}

about:
    home: http://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Aggregate values in FITS headers

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - d2to1
    - stsci.distutils
    - stsci.tools
    - setuptools
    - numpy
    - python x.x
    run:
    - astropy >=1.1
    - stsci.tools
    - numpy
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - fitsblender
