{% set name = 'imexam' %}
{% set version = '0.7.1' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Designed to be a lightweight library which enables users to explore
        data from a command line interface, through a Jupyter notebook or
        through a Jupyter console. It can be used with multiple viewers,
        such as DS9 or Ginga, or without a viewer as a simple library to make
        plots and grab quick photometry information.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - cython
    - pytest
    - setuptools
    - numpy
    - python x.x
    run:
    - astropy >=1.1
    - cython
    - ginga
    - ipython
    - notebook
    - photutils
    - matplotlib
    - scipy
    - numpy
    - python x.x

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - imexam
