{% set name = 'astrolib.coords' %}
{% set version = '0.39.6' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Astronomical coordinates & angular separations

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - setuptools
    - numpy
    - python x.x
    run:
    - numpy
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - astrolib.coords
