{% set name = 'stsci-hst' %}
{% set version = '2.0.0' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci-hst meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - purge_path >=1.0.0
    - acstools >=2.0.0
    - astropy >=1.1
    - calcos >=3.1.8
    - costools >=1.2.1
    - crds >=7.0.1
    - d2to1 >=0.2.12
    - drizzlepac >=2.1.3
    - fitsblender >=0.2.6
    - hstcal >=1.0.0
    - nictools >=1.1.3
    - pyregion >=1.1.2
    - pysynphot >=0.9.8.2
    - reftools >=1.7.1
    - stistools >=1.1
    - stsci.convolve >=2.1.3
    - stsci.distutils >=0.3.8
    - stsci.image >=2.2.0
    - stsci.imagemanip >=1.1.2
    - stsci.imagestats >=1.4.1
    - stsci.ndimage >=0.10.1
    - stsci.numdisplay >=1.6.1
    - stsci.sphinxext >=1.2.2
    - stsci.stimage >=0.2.1
    - stsci.skypac >=0.9
    - stsci.sphere >=0.2
    - stsci.tools >=3.4.1
    - stwcs >=1.2.3
    - wfpc2tools >=1.0.3
    - wfc3tools >=1.3.1
    - numpy
    - python x.x
    run:
    - purge_path >=1.0.0
    - acstools >=2.0.0
    - astropy >=1.1
    - calcos >=3.1.8
    - costools >=1.2.1
    - crds >=7.0.1
    - d2to1 >=0.2.12
    - drizzlepac >=2.1.3
    - fitsblender >=0.2.6
    - hstcal >=1.0.0
    - nictools >=1.1.3
    - pyregion >=1.1.2
    - pysynphot >=0.9.8.2
    - reftools >=1.7.1
    - stistools >=1.1
    - stsci.convolve >=2.1.3
    - stsci.distutils >=0.3.8
    - stsci.image >=2.2.0
    - stsci.imagemanip >=1.1.2
    - stsci.imagestats >=1.4.1
    - stsci.ndimage >=0.10.1
    - stsci.numdisplay >=1.6.1
    - stsci.sphinxext >=1.2.2
    - stsci.stimage >=0.2.1
    - stsci.skypac >=0.9
    - stsci.sphere >=0.2
    - stsci.tools >=3.4.1
    - stwcs >=1.2.3
    - wfpc2tools >=1.0.3
    - wfc3tools >=1.3.1
    - numpy
    - python x.x
