{% set name = 'asv' %}
{% set version = '0.1.1' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        A simple Python history benchmarking tool

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - six
    - sphinx
    - setuptools
    - numpy
    - python x.x
    run:
    - six
    - sphinx
    - numpy
    - python x.x

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
