{% set name = 'pandokia' %}
{% set version = '1.3.11' %}
{% set number = '1' %}

about:
    home: http://ssb.stsci.edu/testing/{{ name }}
    license: BSD
    summary: A test running/reporting facility

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - nose
    - pytest
    - shunit2
    - setuptools
    - python x.x
    run:
    - nose
    - shunit2
    - pytest
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - pdk --help
    imports:
    - pandokia
    - pandokia.runners
    - pandokia.helpers
