{% set name = 'pyregion' %}
{% set version = '1.1.2' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Python parser for ds9 region files

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - numpy
    - pyparsing
    - python x.x
    - setuptools
    run:
    - numpy
    - pyparsing
    - setuptools
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - pyregion
