{% set name = 'pywcs' %}
{% set version = '1.12.1' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Python wrappers to WCSLIB

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - stsci.tools
    - numpy
    - setuptools
    - python x.x
    run:
    - stsci.tools
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - pywcs
