{% set name = 'ext_shmht' %}
{% set version = '0.1' %}
{% set number = '0' %}

about:
    home: https://github.com/stsci-ssb/{{ name }}
    license: BSD
    summary: Shared memory extension

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python x.x
    run:
    - six
    - python x.x

source:
    git_url: https://github.com/stsci-ssb/{{ name }}.git

test:
    imports:
    - ext_shmht
