{% set name = 'selenium' %}
{% set version = '3.4.0' %}
{% set number = '2' %}

about:
    home: https://pypi.python.org/packages/source/s/{{ name }}
    license: BSD
    summary: Python bindings for Selenium

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python
    run:
    - python

source:
    fn: selenium-3.4.0.tar.gz 
    md5: 3f869785a289bd42df1c4d1f65f88df8
    url: https://pypi.python.org/packages/e8/42/3cbe4cbde83a0bf6470c456301f2140d0b315e720660564919766e778e58/selenium-3.4.0.tar.gz
    
test:
    imports:
    - selenium
