{% set name = 'purge_path' %}
{% set version = '1.2.0' %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/{{ name }}
    license: BSD
    summary: purge_path a small PATH manipulator

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - python x.x
    - setuptools
    run:
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/jhunkeler/{{ name }}.git
